### ISSUE TITLE
CRDs missing the metadata property

### ISSUE THREAD

**Issue by jvassev** [cdk8s-team/cdk8s-core#25]
### Description of the bug:

This looks like an import bug or maybe I am not using the API correctly. The generated istio CRD for example misses the metadata property:
```typescript
export interface VirtualServiceProps {
  /**
   * Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
   *
   * @schema VirtualService#spec
   */
  readonly spec?: VirtualServiceSpec;

}
```
As a result if have to use `@ts-ignore` every time I want to provide a name:
```typescript
const vsvc = new VirtualService(this, 'vsvc', {
    // @ts-ignore
    metadata: {
      name: 'cool-service',
    },
    spec: {...}
});
```

Ideally, the VirtualService should look like this:
```typescript
import {ObjectMeta} from './k8s';

export interface VirtualServiceProps {

  /**
   * Standard object metadata.
   *
   * @schema io.k8s.api.apps.v1.Deployment#metadata
   */
  readonly metadata?: ObjectMeta;

  /**
   * Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
   *
   * @schema VirtualService#spec
   */
  readonly spec?: VirtualServiceSpec;

}
```

Granted, the `metadata` property is not present in the schema but all persisted resources have it.

### Reproduction Steps:

Run cdk8s imports with any CRD.

### Environment:

  - **Framework Version**: 1.0.0-beta.10
  - **OS**: Linux

### Other:

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
I've noticed this issue as well with some CRDs I tried importing ([example](https://github.com/grafana-operator/grafana-operator/blob/5450b3501a938b36414259d5a3eecfc71b332094/deploy/olm-catalog/grafana-operator/3.x.x/3.10.0/grafanadashboards.integreatly.org.crd.yaml)), and discovered that it was because the specs omitted the "metadata" property.

However, the kubernetes docs says the "API server validates [metadata] implicitly", and provides [an example](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) without the "metadata" field, so I think it makes sense to add this field automatically for all CRDs.
